### ISSUE TITLE
Update result

### ISSUE THREAD

**Issue by Brooooooklyn** [IWANABETHATGUY/-nodejs-binding-bench#1]
I have published `napi-rs@0.5.1` which including some performance enhancement.

Maybe you should rerun the benchmark and update the results in README

**Comment by IWANABETHATGUY** [comment]
I am not sure if i did anything wrong, but it seems that it's even slower

**Comment by Brooooooklyn** [comment]
@IWANABETHATGUY have you rebuilt the `napi-rs` before running benchmark?

**Comment by Brooooooklyn** [comment]
Running benchmark on my machine:

```
Model Name: MacBook Pro
Model Identifier: MacBookPro15,1
Processor Name: 6-Core Intel Core i7
Processor Speed: 2.6 GHz
Number of Processors: 1
Total Number of Cores: 6
L2 Cache (per Core): 256 KB
L3 Cache: 12 MB
Hyper-Threading Technology: Enabled
Memory: 16 GB
```

### `napi-rs`

```
fibonacci30 x 649 ops/sec ±1.07% (87 runs sampled)
fibonacci40 x 5.23 ops/sec ±1.58% (17 runs sampled)
```

### `neon`

```
fibonacci30 x 622 ops/sec ±1.34% (80 runs sampled)
fibonacci40 x 5.17 ops/sec ±2.64% (17 runs sampled)
```

**Comment by IWANABETHATGUY** [comment]
yes, i rebuild it, same result.Whatever thanks for your work for `napi-rs` , 👍

**Comment by IWANABETHATGUY** [comment]
Awsome
